export default [
  { path: '/', component: '@/pages/index', title: '梁典典的博客' },
  { path: '/category', component: '@/pages/category' },
  { path: '/simple', component: '@/pages/text' },
  { path: '/login', component: '@/pages/login' },
  { path: '/r', component: '@/pages/write' },
  { path: '/push-blog', component: '@/pages/markdown' },
  { path: '/dynamic', component: '@/pages/dynamic' },
  { exact: true, path: '/post/:id', component: '@/pages/post/[id]' },
  { path: '/friends', component: '@/pages/friends' },
  { path: '/setting', component: '@/pages/setting' },
  { path: '/docs', component: '@/pages/docs', title: '梁典典 文档' },
  { exact: true, path: '/user/:id', component: '@/pages/user/[id]' },
  { exact: true, path: '/doc/:id', component: '@/pages/doc/[id]' },
];
